source "https://rubygems.org"

# 2.0.0 satisfies all of the strict requirements we have below
ruby "2.0.0"

gem "middleman", "3.4.1"
gem "middleman-livereload", "3.4.6"
gem "middleman-hashicorp", github: "contiv/middleman-hashicorp"
gem "middleman-blog", "3.5.3"
gem "middleman-deploy", "1.0.0"
gem "middleman-syntax", "2.1.0"
gem "nokogiri", "1.6.7"
gem 'redcarpet', "3.3.4"
gem "rack-protection", ">= 1.5.5"

gem "rouge", "1.10.1"

gem "tzinfo-data", "1.2017.2"
