source "https://rubygems.org"

gem "middleman-livereload", "3.4.6"
gem "middleman-hashicorp", github: "contiv/middleman-hashicorp"
gem "middleman-blog", "3.5.3"
gem "middleman-deploy", "1.0.0"
gem "middleman-syntax", "2.1.0"
gem "nokogiri", "1.3.3"
gem 'redcarpet', "3.3.4"
